// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const style1CLightTheme = {
  'root': TextStyle(
    color: Color(0xff0000ff),
    backgroundColor: Color(0xffffffff),
  ),
  'comment': TextStyle(color: Color(0xff008000)),
  'tag': TextStyle(color: Color(0xff444a)),
  'tag-name': TextStyle(color: Color(0xff444444)),
  'tag-attr': TextStyle(color: Color(0xff444444)),
  'punctuation': TextStyle(color: Color(0xffff0000)),
  'function': TextStyle(color: Color(0xffff0000)),
  'keyword': TextStyle(color: Color(0xffff0000)),
  'attribute': TextStyle(color: Color(0xffff0000)),
  'selector-tag': TextStyle(color: Color(0xffff0000)),
  'doctag': TextStyle(color: Color(0xffff0000)),
  'name': TextStyle(color: Color(0xffff0000)),
  'type': TextStyle(color: Color(0xff0000ff)),
  'params': TextStyle(color: Color(0xff0000ff)),
  'string': TextStyle(color: Color(0xff000000)),
  'number': TextStyle(color: Color(0xff000000)),
  'selector-id': TextStyle(color: Color(0xff000000)),
  'selector-class': TextStyle(color: Color(0xff000000)),
  'quote': TextStyle(color: Color(0xff000000)),
  'template-tag': TextStyle(color: Color(0xff000000)),
  'symbol': TextStyle(color: Color(0xff000000)),
  'deletion': TextStyle(color: Color(0xff000000)),
  'title': TextStyle(color: Color(0xff0000ff)),
  'section': TextStyle(color: Color(0xff0000ff)),
  'regexp': TextStyle(color: Color(0xffab5656)),
  'variable': TextStyle(color: Color(0xffab5656)),
  'template-variable': TextStyle(color: Color(0xffab5656)),
  'link': TextStyle(color: Color(0xffab5656)),
  'selector-attr': TextStyle(color: Color(0xffab5656)),
  'operator': TextStyle(color: Color(0xffab5656)),
  'selector-pseudo': TextStyle(color: Color(0xffab5656)),
  'literal': TextStyle(color: Color(0xffff0000)),
  'built_in': TextStyle(color: Color(0xff0000ff)),
  'bullet': TextStyle(color: Color(0xff0000ff)),
  'code': TextStyle(color: Color(0xff0000ff)),
  'addition': TextStyle(color: Color(0xff0000ff)),
  'meta': TextStyle(color: Color(0xff963200)),
  'meta-string': TextStyle(color: Color(0xff963200)),
  'meta-keyword': TextStyle(color: Color(0xff963200)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
