// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const cybertopiaCherryTheme = {
  'root': TextStyle(color: Color(0xff), backgroundColor: Color(0xff)),
  'comment': TextStyle(color: Color(0xff), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff), fontStyle: FontStyle.italic),
  'code': TextStyle(color: Color(0xff), fontStyle: FontStyle.italic),
  'doctag': TextStyle(color: Color(0xff)),
  'keyword': TextStyle(color: Color(0xff)),
  'formula': TextStyle(color: Color(0xff)),
  'meta-keyword': TextStyle(color: Color(0xff)),
  'section': TextStyle(color: Color(0xff)),
  'name': TextStyle(color: Color(0xff)),
  'selector-tag': TextStyle(color: Color(0xff)),
  'deletion': TextStyle(color: Color(0xff)),
  'subst': TextStyle(color: Color(0xff)),
  'literal': TextStyle(color: Color(0xff)),
  'string': TextStyle(color: Color(0xff)),
  'regexp': TextStyle(color: Color(0xff)),
  'addition': TextStyle(color: Color(0xff)),
  'attribute': TextStyle(color: Color(0xff)),
  'meta-string': TextStyle(color: Color(0xff)),
  'attr': TextStyle(color: Color(0xff)),
  'variable': TextStyle(color: Color(0xff)),
  'template-variable': TextStyle(color: Color(0xff)),
  'type': TextStyle(color: Color(0xff)),
  'selector-class': TextStyle(color: Color(0xff)),
  'selector-attr': TextStyle(color: Color(0xff)),
  'selector-pseudo': TextStyle(color: Color(0xff)),
  'number': TextStyle(color: Color(0xff)),
  'punctuation': TextStyle(color: Color(0xff)),
  'variable.language_': TextStyle(color: Color(0xff)),
  'symbol': TextStyle(color: Color(0xff)),
  'bullet': TextStyle(color: Color(0xff)),
  'link': TextStyle(color: Color(0xff)),
  'meta': TextStyle(color: Color(0xff)),
  'selector-id': TextStyle(color: Color(0xff)),
  'title': TextStyle(color: Color(0xff)),
  'title.function_': TextStyle(color: Color(0xff)),
  'property': TextStyle(color: Color(0xff)),
  'tag': TextStyle(color: Color(0xff)),
  'char.escape_': TextStyle(color: Color(0xff)),
  'built_in': TextStyle(color: Color(0xff)),
  'title.class_': TextStyle(color: Color(0xff)),
  'title.class_.inherited__': TextStyle(color: Color(0xff)),
  'class-title': TextStyle(color: Color(0xff)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'params': TextStyle(color: Color(0xff)),
  'operator': TextStyle(color: Color(0xff)),
  'template-tag': TextStyle(color: Color(0xff)),
};
