// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const felipecTheme = {
  'root': TextStyle(
    color: Color(0xffdedde4),
    backgroundColor: Color(0xff1d1c21),
  ),
  '.hljs::selection': TextStyle(
    color: Color(0xff1d1c21),
    backgroundColor: Color(0xffba9cef),
  ),
  '.hljs-::selection': TextStyle(
    color: Color(0xff1d1c21),
    backgroundColor: Color(0xffba9cef),
  ),
  'comment': TextStyle(color: Color(0xff9e9da4)),
  'code': TextStyle(color: Color(0xff9e9da4)),
  'quote': TextStyle(color: Color(0xff9e9da4)),
  'number': TextStyle(color: Color(0xfff09080)),
  'literal': TextStyle(color: Color(0xfff09080), fontWeight: FontWeight.bold),
  'deletion': TextStyle(color: Color(0xfff09080)),
  'punctuation': TextStyle(color: Color(0xffffbb7b)),
  'meta': TextStyle(color: Color(0xffffbb7b)),
  'operator': TextStyle(color: Color(0xffffbb7b)),
  'subst': TextStyle(color: Color(0xffffbb7b)),
  'doctag': TextStyle(color: Color(0xffffbb7b)),
  'template-variable': TextStyle(color: Color(0xffffbb7b)),
  'selector-attr': TextStyle(color: Color(0xffffbb7b)),
  'type': TextStyle(color: Color(0xfffddb7c)),
  'tag': TextStyle(color: Color(0xffc4da7d)),
  'title': TextStyle(color: Color(0xffc4da7d), fontWeight: FontWeight.bold),
  'selector-class': TextStyle(color: Color(0xffc4da7d)),
  'selector-id': TextStyle(color: Color(0xffc4da7d)),
  'string': TextStyle(color: Color(0xff93e4a4)),
  'regexp': TextStyle(color: Color(0xff93e4a4)),
  'addition': TextStyle(color: Color(0xff93e4a4)),
  'class': TextStyle(color: Color(0xff65e7d1)),
  'property': TextStyle(color: Color(0xff65e7d1)),
  'name': TextStyle(color: Color(0xff30c2d8)),
  'selector-tag': TextStyle(color: Color(0xff30c2d8)),
  'keyword': TextStyle(color: Color(0xff5fb8f2)),
  'built_in': TextStyle(color: Color(0xff5fb8f2)),
  'section': TextStyle(color: Color(0xff90aafa)),
  'bullet': TextStyle(color: Color(0xff90aafa)),
  'selector-pseudo': TextStyle(color: Color(0xffba9cef)),
  'variable': TextStyle(color: Color(0xffd991d2)),
  'params': TextStyle(color: Color(0xffd991d2)),
  'attr': TextStyle(color: Color(0xffd991d2)),
  'attribute': TextStyle(color: Color(0xffd991d2)),
  'symbol': TextStyle(color: Color(0xffec8dab)),
  'link': TextStyle(color: Color(0xffec8dab)),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
};
