// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const rosePineTheme = {
  'meta': TextStyle(color: Color(0xff6e6a86)),
  'comment': TextStyle(color: Color(0xff6e6a86)),
  'tag': TextStyle(color: Color(0xffeb6f92)),
  'doctag': TextStyle(color: Color(0xffeb6f92)),
  'selector-id': TextStyle(color: Color(0xffeb6f92)),
  'selector-class': TextStyle(color: Color(0xffeb6f92)),
  'regexp': TextStyle(color: Color(0xffeb6f92)),
  'template-tag': TextStyle(color: Color(0xffeb6f92)),
  'selector-pseudo': TextStyle(color: Color(0xffeb6f92)),
  'selector-attr': TextStyle(color: Color(0xffeb6f92)),
  'variable.language_': TextStyle(color: Color(0xffeb6f92)),
  'deletion': TextStyle(color: Color(0xffeb6f92)),
  'variable': TextStyle(color: Color(0xffebbcba)),
  'template-variable': TextStyle(color: Color(0xffebbcba)),
  'number': TextStyle(color: Color(0xffebbcba)),
  'literal': TextStyle(color: Color(0xffebbcba)),
  'type': TextStyle(color: Color(0xffebbcba)),
  'params': TextStyle(color: Color(0xffebbcba)),
  'link': TextStyle(color: Color(0xffebbcba)),
  'built_in': TextStyle(color: Color(0xfff6c177)),
  'attribute': TextStyle(color: Color(0xfff6c177)),
  'selector-tag': TextStyle(color: Color(0xff9ccfd8)),
  'keyword': TextStyle(color: Color(0xffc4a7e7)),
  'title.function_': TextStyle(color: Color(0xff9ccfd8)),
  'title': TextStyle(color: Color(0xff9ccfd8)),
  'title.class_': TextStyle(color: Color(0xff9ccfd8)),
  'title.class_.inherited__': TextStyle(color: Color(0xff9ccfd8)),
  'subst': TextStyle(color: Color(0xff9ccfd8)),
  'property': TextStyle(color: Color(0xff9ccfd8)),
  'quote': TextStyle(color: Color(0xff31748f)),
  'string': TextStyle(color: Color(0xff31748f)),
  'symbol': TextStyle(color: Color(0xff31748f)),
  'bullet': TextStyle(color: Color(0xff31748f)),
  'addition': TextStyle(color: Color(0xff31748f)),
  'code': TextStyle(color: Color(0xffebbcba)),
  'formula': TextStyle(color: Color(0xffebbcba)),
  'section': TextStyle(color: Color(0xffebbcba)),
  'name': TextStyle(color: Color(0xffc4a7e7)),
  'operator': TextStyle(color: Color(0xffc4a7e7)),
  'char.escape_': TextStyle(color: Color(0xffc4a7e7)),
  'attr': TextStyle(color: Color(0xffc4a7e7)),
  'punctuation': TextStyle(color: Color(0xffe0def4)),
  'root': TextStyle(
    backgroundColor: Color(0xff191724),
    color: Color(0xff6e6a86),
  ),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
