// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const rosePineDawnTheme = {
  'meta': TextStyle(color: Color(0xff9893a5)),
  'comment': TextStyle(color: Color(0xff9893a5)),
  'tag': TextStyle(color: Color(0xffb4637a)),
  'doctag': TextStyle(color: Color(0xffb4637a)),
  'selector-id': TextStyle(color: Color(0xffb4637a)),
  'selector-class': TextStyle(color: Color(0xffb4637a)),
  'regexp': TextStyle(color: Color(0xffb4637a)),
  'template-tag': TextStyle(color: Color(0xffb4637a)),
  'selector-pseudo': TextStyle(color: Color(0xffb4637a)),
  'selector-attr': TextStyle(color: Color(0xffb4637a)),
  'variable.language_': TextStyle(color: Color(0xffb4637a)),
  'deletion': TextStyle(color: Color(0xffb4637a)),
  'variable': TextStyle(color: Color(0xffd7827e)),
  'template-variable': TextStyle(color: Color(0xffd7827e)),
  'number': TextStyle(color: Color(0xffd7827e)),
  'literal': TextStyle(color: Color(0xffd7827e)),
  'type': TextStyle(color: Color(0xffd7827e)),
  'params': TextStyle(color: Color(0xffd7827e)),
  'link': TextStyle(color: Color(0xffd7827e)),
  'built_in': TextStyle(color: Color(0xffea9d34)),
  'attribute': TextStyle(color: Color(0xffea9d34)),
  'selector-tag': TextStyle(color: Color(0xff56949f)),
  'keyword': TextStyle(color: Color(0xff907aa9)),
  'title.function_': TextStyle(color: Color(0xff56949f)),
  'title': TextStyle(color: Color(0xff56949f)),
  'title.class_': TextStyle(color: Color(0xff56949f)),
  'title.class_.inherited__': TextStyle(color: Color(0xff56949f)),
  'subst': TextStyle(color: Color(0xff56949f)),
  'property': TextStyle(color: Color(0xff56949f)),
  'quote': TextStyle(color: Color(0xff286983)),
  'string': TextStyle(color: Color(0xff286983)),
  'symbol': TextStyle(color: Color(0xff286983)),
  'bullet': TextStyle(color: Color(0xff286983)),
  'addition': TextStyle(color: Color(0xff286983)),
  'code': TextStyle(color: Color(0xffd7827e)),
  'formula': TextStyle(color: Color(0xffd7827e)),
  'section': TextStyle(color: Color(0xffd7827e)),
  'name': TextStyle(color: Color(0xff907aa9)),
  'operator': TextStyle(color: Color(0xff907aa9)),
  'char.escape_': TextStyle(color: Color(0xff907aa9)),
  'attr': TextStyle(color: Color(0xff907aa9)),
  'punctuation': TextStyle(color: Color(0xff575279)),
  'root': TextStyle(
    backgroundColor: Color(0xfffaf4ed),
    color: Color(0xff575279),
  ),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
